frr version 9.1
frr defaults traditional
hostname onprem-r1
service integrated-vtysh-config
log syslog informational
!
interface lo
 ip address 10.99.1.1/32
!
interface eth1
 description transit-to-onprem-r2
 ip address 172.31.12.1/30
!
router bgp 65101
 bgp router-id 10.99.1.1
 no bgp ebgp-requires-policy
 neighbor 172.31.12.2 remote-as 65102
 neighbor 172.31.12.2 description onprem-r2-core
 !
 address-family ipv4 unicast
  network 10.99.1.1/32
 exit-address-family
!
line vty
!
