frr version 9.1
frr defaults traditional
hostname onprem-r2
service integrated-vtysh-config
log syslog informational
!
interface lo
 ip address 10.99.2.2/32
!
interface eth1
 description transit-to-onprem-r1
 ip address 172.31.12.2/30
!
interface eth2
 description onprem-lan
 ip address 172.31.20.1/24
!
router bgp 65102
 bgp router-id 10.99.2.2
 no bgp ebgp-requires-policy
 neighbor 172.31.12.1 remote-as 65101
 neighbor 172.31.12.1 description onprem-r1-edge
 !
 address-family ipv4 unicast
  network 10.99.2.2/32
  network 172.31.20.0/24
 exit-address-family
!
line vty
!
